app/updown/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length
# from wtforms import ValidationError


class UploadForm(FlaskForm):
    file = FileField('上传文件', validators=[FileRequired('文件未选择！'),
                                         FileAllowed(['jpg', 'png', 'torrent', 'txt'],
                                                     '只允许上传jpg png torrent以及txt文件')])
    note = StringField('文件说明', validators=[DataRequired(), Length(2, 64,
                                           message='请认真填写文件说明，但不能超过64个字符')])
    hashname = BooleanField('上传时随机文件名（选择此项后请认真填写文件说明）')
    submit = SubmitField('确认上传')

    def validate_file(self, field):
        # 验证文件大小? 验证文件名长度? 验证文件名是否重复?
        pass

app/updown/__init__.py
from flask import Blueprint

updown = Blueprint('updown', __name__)

from . import views

app/updown/views.py
from flask import render_template, abort, redirect, request, url_for, flash, send_from_directory
from ..models import Updown
from flask_login import login_required, current_user
from .forms import UploadForm
from . import updown
from .. import db
import os
from werkzeug.utils import secure_filename
from ..decorators import admin_required


@updown.route('/disable/<id>')
@login_required
@admin_required
def download_disable(id):
    file = Updown.query.get_or_404(id)
    file.disabled = True
    db.session.add(file)
    db.session.commit()
    return redirect(url_for('updown.updown',
                            page=request.args.get('page', 1, type=int)))


@updown.route('/enable/<id>')
@login_required
@admin_required
def download_enable(id):
    file = Updown.query.get_or_404(id)
    file.disabled = False
    db.session.add(file)
    db.session.commit()
    return redirect(url_for('updown.updown',
                            page=request.args.get('page', 1, type=int)))


@updown.route('/download/<filename>')
def download(filename):
    if os.path.isfile(os.path.join('app/updown/download/', filename)):
        # 此处有个坑 os.path是以项目根目录搜索
        # 而flask的send_from_directory方法是从app根目录开始搜索
        flash('开始下载：' + filename, category='info')
        return send_from_directory('updown/download/', filename, as_attachment=True)
    else:
        flash('抱歉，文件没有在服务器上找到', category='error')
        return abort(404)


@updown.route('/', methods=['GET', 'POST'])
# 暂时不要求注册帐号才能访问 @login_required
def updown():
    form = UploadForm()
    if form.validate_on_submit():
        if not request.files['file']:
            flash('上传失败 请重试', category='error')
            return redirect(url_for('.updown'))
        file = request.files['file']  # 直接从request对象中获取file
        filename = secure_filename(file.filename)
        extension = os.path.splitext(filename)[1][1:]  # 取扩展名并丢掉'.'
        filename = os.path.splitext(filename)[0]  # 取文件名
        if form.hashname.data:
            filename = Updown.filename_hash(filename)
        upload = Updown(filename=filename,
                        extension=extension,
                        uploader=current_user.id,
                        note=form.note.data)
        try:
            file.save('app/updown/download/' + filename + '.' + extension)
            # request对象中的file对象的save方法同样从项目根目录开始寻找目录
            flash('上传成功', category='message')
            db.session.add(upload)
            db.session.commit()
        except FileExistsError as e:
            flash('同名文件已存在，上传失败', category='error')
        except Exception as e:
            flash('上传失败', category='error')
        return redirect(url_for('.updown'))
    query = Updown.query
    # 显示服务器上的文件
    pagination = query.order_by(Updown.timestamp.desc()).paginate(per_page=20)
    files = pagination.items
    return render_template('updown/updown.html',
                           upform=form,
                           files=files,
                           pagination=pagination)

app/templates/updown/updown.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Xudong - Up&Down{% endblock %}

{% block page_content %}
<div class="page-header">
<h2>Up & Down</h2>
    {% if current_user.can(Permission.ADMIN) %}
        <h4>您拥有上传文件的权限，但请善用权限，不要上传无用文件。</h4>
    <div class="upload-form">
        {{ wtf.quick_form(upform) }}
    </div>
    {% else %}
        <p>您没有上传文件的权限，但可以下载资源。</p>
    {% endif %}
</div>

<table class="table">
    <thead>
        <th class="active hidden-xs">文件名</th>
        <th class="active">类型</th>
        <th class="active">时间</th>
        <th class="active">上传者</th>
        <th class='active'>说明</th>
        <th class='active'>下载</th>
    </thead>
    <tbody>
        {% for file in files %}

            <!-- tr -->
            {% if file.disabled %} <tr class="bg-danger">
            {% else %}
            <tr class="bg-success"> {% endif %}
                <td class="hidden-xs">{{ file.filename }}
                {% if current_user.can(Permission.ADMIN) %}
                    {% if file.disabled %}
                        <a class="btn btn-default btn-xs" href="{{ url_for('updown.download_enable', id=file.id) }}">启用</a>
                    {% else %}
                        <a class="btn btn-danger btn-xs" href="{{ url_for('updown.download_disable', id=file.id) }}">禁用</a>
                    {% endif %}
                {% endif %}
                </td>
                <td>{{ file.extension }}</td>
                <td>{{ moment(file.timestamp).fromNow() }}</td>
                <td>
                <a  href="{{ url_for('main.user', username=file.uploader_user.username) }}">
                    {{ file.uploader_user.username }}
                </a>
                </td>
                <td>{{ file.note }}</td>
                <td>
                    {% if not file.disabled %}
                    <a href="{{ url_for('updown.download', filename=file.filename+'.'+file.extension) }}"
                       class="btn btn-success btn-xs" role ="button">下载</a>
                    {% else %}
                    <a class="btn btn-danger btn-xs" role ="button">禁用</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

    </tbody>
</table>


{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.updown')}}
</div>
{% endif %}
{% endblock %}